### ISSUE TITLE
Wireframe questions

### ISSUE THREAD

**Issue by verusbabb** [brandyquinlan/PAIR#4]
The wireframes are looking great.  Questions:

1. are landing page and wireframe v1 alternatives of the same page?
2. love how you are already outlining some and JS needs in the wireframes.
3. have a few questions to understand design whenever you all want to talk?  I am always pretty flexible.

**Comment by katsign** [comment]
Good deal.

1) They are the same page, this is an updated version I made after we talked more / I thought more about functionality.
2) Glad it reads, there is one error I made where something is colored as HTML that should be red for JS: the "REVEAL DIV" actions on Landing page.
3) Could we chat again as a group on Tuesday night? I am headed to the Smokies for a couple days in a cabin out there and won't be using my computer.

The big picture questions that will help me start coding the HTML / CSS : 
**Do we like this page structure?** 
Two pages accessed from nav (HOME, FAVORITES) and hidden RESULTS page generated from click event on Search.
**Do we like the idea of using Materialize?** 
I read through their Documentation last night and got really excited about it, it's nice and simple. Thanks for mentioning it, Steve!
